### ISSUE TITLE
Enhancement: Long press to select (multiple)

### ISSUE THREAD

**Issue by spacecowboy** [andersericsson/MultiColumnList#1]
Are their any plans to support selecting multiple items to share,delete etc?

**Comment by andersericsson** [comment]
Adding long press support is not that much work actually. Then supporting selecting multiple is possible to implement. But as I see it, that would not be implemented in the view, but rather the app code instead.

**Comment by spacecowboy** [comment]
Yes, with a listener. Just wondered if there are any plans.
Den 19 feb 2014 10:42 skrev "Anders Ericsson" notifications@github.com:

**Comment by andersericsson** [comment]
I've added support for long press to it now. Also made some additions to MainActivity to enable a select multiple mode.

**Comment by spacecowboy** [comment]
Cool :)
